Add /ban and /unban
l1ttle-org/BanSystem pull request #2
Opened 2021-01-05 13:45 UTC by ItsAlvinThePro

2021-01-05 13:51 UTC, l1ttleO requested changes
Also remove the `testplugin` entries

2021-01-05 13:51 UTC, l1ttleO commented on src/main/resources/plugin.yml
> +    ban:
```suggestion
  ban:
```

2021-01-05 13:51 UTC, l1ttleO commented on src/main/resources/plugin.yml
> +    description: Bans a player silently/unsilenty with a ban reason.
```suggestion
    description: Bans a player. Ban reason is required, use `-s` to ban silently
```

2021-01-05 13:51 UTC, l1ttleO commented on src/main/resources/plugin.yml
> +    permission: banplugin.ban
```suggestion
    permission: bansystem.ban
```

2021-01-05 13:51 UTC, l1ttleO commented on src/main/resources/plugin.yml
> +    permission-message: You are not a high enough rank to ban someone!
```suggestion
```

2021-01-05 13:51 UTC, l1ttleO commented on src/main/resources/plugin.yml
> +    description: Unbans a player silenty/unsilenty.
```suggestion
    description: Unbans a player. Use '-s' to unban silently
```

2021-01-05 13:51 UTC, l1ttleO commented on src/main/resources/plugin.yml
> +    permission: banplugin.unban
```suggestion
    permission: bansystem.unban
```

2021-01-05 13:51 UTC, l1ttleO commented on src/main/resources/plugin.yml
> +    permission-message: You are not a high enough rank to unban someone!
```suggestion
```

2021-01-05 13:55 UTC, l1ttleO commented on src/main/resources/plugin.yml
> +    permission-message: You are not a high enough rank to unban someone!
```suggestion
```

2021-01-05 13:57 UTC, l1ttleO submitted a review, later dismissed
Add permission entries and remove testplugin entries

2021-01-05 15:00 UTC, ItsAlvinThePro commented
HELLO!

2021-01-11 16:18 UTC, l1ttleO approved these changes

2021-01-11 16:19 UTC, merged